### ISSUE TITLE
attention

### ISSUE THREAD

**Issue by LZDOscar** [FactomProject/factom-walletd#16]
Hello, I have a one problem here. If i use 'compose-chain' method ,  how can i get 'chainid'?This method will return the appropriate api calls (“commit-chain"and“reveal-chain")to create a chain in factom, not have chainid.....
Thanks for reply

**Comment by PaulBernier** [comment]
@LZDOscar you will only get the chainid once you submit the result of `compose-chain` to `commit-chain` API, this API will return the chainid: https://docs.factomprotocol.org/start/factom-api-docs/factomd-api#commit-chain
