### ISSUE TITLE
Cannot send Factoids

### ISSUE THREAD

**Issue by FaguiCurtain** [FactomProject/factom-walletd#3]
i described my problem on Reddit here:

https://www.reddit.com/r/factom/comments/50dwxs/wallet_for_macos/

i am using the latest version of MacOS El Capitan 10.11.5

I can send my coins to the my Factoid Address without problem

the problem is when i sign a transaction and want to send it, i do have a popping up window, i say yes, but no sign of the message "transaction UITX has been submitted to Factom"

tried several times. actually after a while, the message appeared, but in the meantime, i sent the coins again, so i sent them twice !

trying again, but same behaviour: no confirmation message that the transaction has been submitted to Factom. Waiting but nothing happens;

Also, the transactions from the prior sessions have been deleted without control it seems that I overwrote it too easily, that sucks

Please help ! thanks

**Comment by carryforward** [comment]
this is the repo for an unreleased wallet.
