### ISSUE TITLE
Control Panel not resolving

### ISSUE THREAD

**Issue by eolszewski** [FactomProject/factom-walletd#62]
localhost:8090 is not serving this content

**Comment by carryforward** [comment]
oh, sorry, the wallet does not have the control panel.  factomd does, though.

factomd needs to be run for the factom-walletd to be effective.

control panel looks like this: https://twitter.com/deery_me/status/921160734171631618

**Comment by eolszewski** [comment]
Ah, misread the logs, closing this.
