### ISSUE TITLE
Add flag to override config location

### ISSUE THREAD

**Issue by PaulBernier** [FactomProject/factom-walletd#72]
`factomd` has this flag `-config` that allows to specify the location of the config file to read. 
```
  -config string
    	Override the config file location (factomd.conf)
```

In `walletd` the file location is harcoded, so I would like to introduce a similar flag. That would be a backward compatible change.

I'm willing to make that change, if you could provide me with a branch to make a PR against/

**Comment by carryforward** [comment]
That sounds like a great addition.  Branches FD-899_config_path have been created in both factom-walletd and factom repositories.  looking forward to the pull request.

**Comment by PaulBernier** [comment]
Any chance this will make it to a new version of walletd in the near future?

**Comment by carryforward** [comment]
indeed, this is on the way to release.  We are concentrating on getting Parchment out, and while Xuan is getting built, all the updates to the CLI and walletd we are trying to get to the master branch.

**Comment by PaulBernier** [comment]
Merged
