### ISSUE TITLE
Don't allow remote connections by default

### ISSUE THREAD

**Issue by WhoSoup** [FactomProject/factom-walletd#79]
Hey, this is a security issue that pops up quite frequently. By default, factom-walletd accepts all remote connections. This is not great for casual users as anyone who knows their IP can connect to the wallet and the additional steps of securing the wallet behind a firewall are cumbersome and there are no instructions for it available in the factom ecosphere.

It would be very simple to lock connections to localhost only and require users to explicitly allow remote connections. This is a working example: https://github.com/WhoSoup/factom-walletd/commit/5f6457225c0ec385a8efb9db9b54a15be3c3d7d0

Is that a desirable feature to include, or should it be the opposite way around (ie, it's open by default but people can close it via `--local` or similar)?

**Comment by PaulBernier** [comment]
Merged and published as v3.0 (as it changes the default behavior)
